### ISSUE TITLE
Course surveys tracking

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#374]
This is a list of assorted small bugs that need to be fixed

- [x] rating panel with too many ratings should scroll
- [x] round rating numbers to 2 decimal places
- [x] icsr without ratings should say "no ratings" and not blank
- [x] search panel display looks scrollable but actually is not
