### ISSUE TITLE
Candidate logistics tracking improvements

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#462]
- [ ] Make common requirement class with Title, Description, optional Committee, optional Event type
- [ ] Make accessible checkoff UI
- [ ] The candidate portal should be less than 400 Python statements

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/464
