### ISSUE TITLE
Candidate Revamp followups

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#465]
- [x] Events RSVP confirm panel has the status and action columns combined into a single checkbox column. On click it'll do the correct confirm/unconfirm action
- [x] Leverage events RSVP template code to enable officers to check candidates off for misc reqs
- [x] Enable this pipeline: during CM, VP tells all the candidates to make an account, RSVP to CM (an external event), and enter the attendance form password. As soon as they're confirmed, their account becomes a candidate account
- [x] Events calendar scrolls for no reason
- [x] Officer portal checkoff scrolls back to summary
- [x] Summary shows totals at the bottom
- [x] Summary shows number of completed if not completed
- [x] Events calendar crashes on anonymous user access

_Originally posted by @bri25yu in https://github.com/compserv/hknweb/pull/464#issuecomment-1118930370_

**Comment by bri25yu** [comment]
[Reducing candidate portal text lengths](https://github.com/bri25yu/hknweb/commit/c756d30a7d6f08f6ef6b00adf5f6796824e7c546)

**Comment by bri25yu** [comment]
[Converting events RSVP to checkboxes](https://github.com/bri25yu/hknweb/commit/ee5b5bdb8488a5be2b6997e366b46c0110d5138b)
[Converting officer req checkoffs to checkboxes](https://github.com/bri25yu/hknweb/commit/cdb398fe59e4a1280095862946310fd06089a061)
